version: '3.8'

services:
  nextjs:
    image: node:18-alpine  # Use the official Node.js image
    working_dir: /app  # Set the working directory inside the container
    volumes:
      - .:/app  # Bind mount the current directory to /app in the container
    ports:
      - "3000:3000"  # Expose port 3000
    command: >
      sh -c "npm install && npm run build && npm run start"  # Install dependencies, build, and start the app
    depends_on:
      - postgres  # Ensure that the Postgres service is running before starting Next.js

  postgres:
    image: postgres:15-alpine  # Use a lightweight Postgres image
    environment:
      POSTGRES_USER: icarboni
      POSTGRES_PASSWORD: pokeAPIpassword
      POSTGRES_DB: pokeAPI
    ports:
      - "5432:5432"  # Expose the default PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist Postgres data

volumes:
  postgres_data:
